### ISSUE TITLE
Java 8: jabax.bind not found.

### ISSUE THREAD

**Issue by haynesgt** [emailage/Emailage_Java#3]
Need to add the following jar or use non-deprecated libraries instead:

http://central.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar

**Comment by briandowns** [comment]
Thanks for reporting this. We'll take a look.

**Comment by briandowns** [comment]
Thanks for filing this issue. Can you point out in this project where we'd need to update?

**Comment by briandowns** [comment]
Closing this issue since we're not using any dependencies. Please reopen if this is closed in error.
