### ISSUE TITLE
Wrapper is no longer working against the sandbox environment

### ISSUE THREAD

**Issue by jimmymain** [emailage/Emailage_Java#32]
I have been using the wrapper for some time, but something has definitely changed recently that is causing this java implementation to fail on the sandbox environment.

The exact same credentials used with the dotNetCore wrapper work just fine (Using the sandbox enum and sandbox credentials). I am also able to get a bearer token from the sandbox using the same credentials with a raw POST. The wrapper fails to authenticate at the moment though.

I am convinced that something has changed recently on the sandbox environment as to render this code now incorrect.
It would be good if someone could investigate, alternatively we might have to just use the raw API. This wrapper has been very convenient up until now, and it does still work against the production environment.

**Comment by iarekk** [comment]
Hi @jimmymain we're investigating, I hope to have an update for you in the next few days

**Comment by jimmymain** [comment]
Thanks!
There is definitely something not correct on UAT.

**Comment by jimmymain** [comment]
Any news on this issue @iarekk

**Comment by aburra12** [comment]
Hello @jimmymain I am currently investigating this issue. Could you please let me know if you are using OAuth1 or OAuth2 for authentication? Thank you.

**Comment by aburra12** [comment]
just an update here @jimmymain I tried to run tests from TestClient.java by setting Enums.Environment environment to Enums.Environment.Sandbox, replaced accountSid and authToken strings with appropriate values and got success for both OAUTH1 and OAUTH2 auth types. Here's a screenshot of the results. Could you let me know the exact error you are seeing so I can debug further? Thank you

![image](https://user-images.githubusercontent.com/55166604/128074654-4a6cecbe-8bcf-4de8-9717-ada5deae2320.png)

**Comment by jimmymain** [comment]
Please email me craig@palantir.co.za and I will send you the details.

**Comment by iarekk** [comment]
@jimmymain Anu reached out to that email address last Thursday, but we haven't heard back - is the issue still affecting you?

**Comment by iarekk** [comment]
We've followed up privately, and the issue seems to be resolved. No code changes needed in the client.
